database password is required in the configuration file

diff --git a/migrate b/migrate
--- a/migrate
+++ b/migrate
@@ -33,5 +33,11 @@ if [ -z "$db_user" ]; then
     error "Please specify the user migrate should use to connect to the database in the config file"
     exit 1
 fi
+if [ -z "$db_password" ]; then
+    error "ERROR: Missing required configuration setting 'db_password' in 'migrations/config'."
+    error "Please specify the password migrate should use to connect to the database in the config file"
+    exit 1
+fi
+
 
 echo "SUCCESS"
