migrate now actually executes migrations

diff --git a/migrate b/migrate
--- a/migrate
+++ b/migrate
@@ -44,35 +44,78 @@ if [ -z "$db_name" ]; then
     exit 1
 fi
 
-for f in migrations/*; do
-    if echo $f | grep "^migrations/.*\.sql$" >/dev/null; then
-        mysql_out=$(mysql --host="$db_host" --user="$db_user" --password="$db_password" --database="$db_name" < $f 2>&1)
-        if [ $? != 0 ]; then
-            # attempt to convert the errors given by MySQL to errors which
-            # provide the user context
-            if echo $mysql_out | grep "^ERROR 2005 (HY000): Unknown MySQL server host '$db_host' (0)$" >/dev/null; then
-                error "ERROR: Cannot connect to host '$db_host'."
-                error "Is the host specified in the configuration file up and reachable?"
-            elif echo $mysql_out | grep "^ERROR 1045 (28000): Access denied for user '$db_user'@'$db_host' (using password: NO)" >/dev/null; then
-                error "ERROR: Access denied for database user '$db_user'."
-                error "Is the username '$db_user' specified in the configuration correct?"
-            elif echo $mysql_out | grep "^ERROR 1045 (28000): Access denied for user '$db_user'@'$db_host' (using password: YES)" >/dev/null; then
-                error "ERROR: Access denied for user '$db_user'."
-                error "Is the password specified in the configuration file correct?"
-            elif echo $mysql_out | grep "^ERROR 1044 (42000): Access denied for user '$db_user'@'$db_host' to database '$db_name'" >/dev/null; then
-                error "ERROR: Access denied to database with name '$db_name'."
-                error "Is the database name specified in the configuration file correct?"
-                error "Does the specified database exist?"
-                error "Does the specified user have access privileges to the specified database?"
-            else
-                error "ERROR: the database returned the following error:"
-                error "$mysql_out"
-            fi
-            exit 1
+catch_mysql_error() {
+    if [ $? != 0 ]; then
+        # attempt to convert the errors given by MySQL to errors which
+        # provide the user context
+        if echo $mysql_out | grep "^ERROR 2005 (HY000): Unknown MySQL server host '$db_host' (0)$" >/dev/null; then
+            error "ERROR: Cannot connect to host '$db_host'."
+            error "Is the host specified in the configuration file up and reachable?"
+        elif echo $mysql_out | grep "^ERROR 1045 (28000): Access denied for user '$db_user'@'$db_host' (using password: NO)" >/dev/null; then
+            error "ERROR: Access denied for database user '$db_user'."
+            error "Is the username '$db_user' specified in the configuration correct?"
+        elif echo $mysql_out | grep "^ERROR 1045 (28000): Access denied for user '$db_user'@'$db_host' (using password: YES)" >/dev/null; then
+            error "ERROR: Access denied for user '$db_user'."
+            error "Is the password specified in the configuration file correct?"
+        elif echo $mysql_out | grep "^ERROR 1044 (42000): Access denied for user '$db_user'@'$db_host' to database '$db_name'" >/dev/null; then
+            error "ERROR: Access denied to database with name '$db_name'."
+            error "Is the database name specified in the configuration file correct?"
+            error "Does the specified database exist?"
+            error "Does the specified user have access privileges to the specified database?"
+        else
+            error "ERROR: the database returned the following error:"
+            error "$mysql_out"
         fi
+        exit 1
+    fi
+}
+
+MYSQL_COMMAND="mysql --host=$db_host --user=$db_user --password=$db_password --database=$db_name"
+
+run_mysql_file () {
+    file=$1
+    if [ ! -r "$file" ]; then
+        error "Cannot execute '$file', because it is not found"
+        exit 1
+    fi
+    mysql_out=$($MYSQL_COMMAND < $file 2>&1)
+    catch_mysql_error
+    return $mysql_out
+}
+
+run_mysql_query () {
+    sql=$1
+    mysql_out=$(echo "$sql" | mysql --host="$db_host" --user="$db_user" --password="$db_password" --database="$db_name" 2>&1)
+    catch_mysql_error
+    return $mysql_out
+}
+
+# verify database connection
+run_mysql_file /dev/null
+
+# check for migrations table
+echo "* checking for migration tables \c"
+out=$(run_mysql_query "SHOW TABLES like 'migrations'")
+if [ "z$out" = "z" ]; then
+    # migrations table does not exist, create it
+    echo "[MISSING]"
+    echo "- creating migration tables \c"
+    run_mysql_query "CREATE TABLE migrations (id INT UNIQUE)"
+    echo "[OK]"
+else
+    echo "[OK]"
+fi
+
+# actually execute the migrations
+echo "* executing migrations"
+for f in migrations/*; do
+    if echo "$f" | grep "^migrations/.*\.sql$" >/dev/null; then
+        # execute migration
+        echo "- executing $f \c"
+        run_mysql_file "$f"
+        echo "[OK]"
     fi
 done
 
 echo "Migrate ran successfully."
-echo "However there were no migrations executed as none were found in the migrations directory"
 exit 0
