error and exit when migrations are added with a lower id than the previously executed migration

diff --git a/migrate b/migrate
--- a/migrate
+++ b/migrate
@@ -107,18 +107,28 @@ else
 fi
 
 # NOTE: tail +2 skips the first header line
-executed_migrations=$(run_mysql_query "SELECT id FROM migrations" | tail +2)
+executed_migrations=$(run_mysql_query "SELECT id FROM migrations ORDER BY id" | tail +2)
 
 # actually execute the migrations
 echo "* executing migrations"
+executed_max_id=$(($(echo $executed_migrations | tail -1)))
 for f in $(ls migrations | sort -n); do
     if echo "$f" | grep "^[0-9][0-9]*.*\.sql$" >/dev/null; then
         # execute migration
-        # NOTE: here we also strip any potential leading zeroes, except when it's the last
+        # NOTE: here we also strip any potential leading zeroes, except when
+        # it's the last number
         migration_id=$(echo "$f" | sed -n 's,^0*\([0-9][0-9]*\).*$,\1,p')
-        if echo "$executed_migrations" | grep "$migration_id" >/dev/null; then
+
+        if echo "$executed_migrations" | grep "^$migration_id$" >/dev/null; then
             echo "- already executed migrations/$f"
         else
+
+            # error when previously executed migration id is higher than the current one
+            if [ ! $migration_id -gt $executed_max_id ]; then
+                error "ERROR: migrations/$f has not been executed, but a higher migration with id $executed_max_id has already been executed"
+                exit 1
+            fi
+
             echo "- executing migrations/$f"
             run_mysql_file "migrations/$f" >/dev/null
             run_mysql_query "INSERT INTO migrations SET id = '$migration_id'" >/dev/null
