config requires database host to be specified

diff --git a/migrate b/migrate
--- a/migrate
+++ b/migrate
@@ -1,15 +1,31 @@
 #!/bin/sh
 
+error () {
+    echo $* 1>&2
+}
+
 # check for migrations subdirectory in current directory
 if [ ! -d "migrations" ]; then
-    echo "ERROR: Directory 'migrations' not found.\nDid you initialize migrations for this project?" 1>&2
+    error "ERROR: Directory 'migrations' not found.\nDid you initialize migrations for this project?"
     exit 1
 fi
 
 # check for configuration file named 'config' in migrations directory
 if [ ! -f "migrations/config" ]; then
-    echo "ERROR: Configuration 'migrations/config' not found." 1>&2
-    echo "Please add the configuration file named 'config' to the migrations directory" 1>&2
+    error "ERROR: Configuration 'migrations/config' not found."
+    error "Please add the configuration file named 'config' to the migrations directory"
     exit 1
 fi
 
+# TODO: hmm, is there a better way to read configs in bash? when there is
+# something wrong in the config file (syntax error perhaps) that can lead to
+# the migrate script crashing...
+. migrations/config
+
+if [ -z "$db_host" ]; then
+    error "ERROR: Missing required configuration setting 'db_host' in 'migrations/config'."
+    error "Please specify the hostname migrate should connect to in the config file"
+    exit 1
+fi
+
+echo "SUCCESS"
